name: actividad_1_1

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: paso1 - crea entorno virtual
        run: python -m venv venv
      - name: paso2 - activar entorno virtual
        run: ./venv/Scripts/activate   
      - name: paso3 - actualizar pip
        run: |
          call venv\Scripts\activate
          python -m pip install --upgrade pip
      - name: paso4 - instalar dependencias
        run: |
          call venv\Scripts\activate
          pip install -e .
          pip install requests
      - name: verificar paquetes instalados
        run: |
          call venv\Scripts\activate
          pip list
      - name: paso5 - Ejecutar script
        run: |
          call venv\Scripts\activate
          python src/pad_2025/Jazmin_actividad_1.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Test
          commit_user_name: Jazmin Ortiz [GitHub Actions]
          commit_user_email: jazmin.ortiz@est.iudigital.edu.co
          commit_author: Jazmin Ortiz <jazmin.ortiz@est.iudigital.edu.co>
