name: actividad_1_1

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: paso1 - Checkout del repositorio
        uses: actions/checkout@v4

      - name: paso2 - Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: paso3 - Actualizar pip globalmente antes de crear el entorno virtual
        run: python -m pip install --upgrade pip

      - name: paso4 - Crear entorno virtual
        run: python -m venv venv

      - name: paso5 - Verificar que la carpeta `venv` existe
        run: dir venv

      - name: paso6 - Instalar dependencias en el entorno virtual
        run: venv\Scripts\python.exe -m pip install -e .

      - name: paso7 - Instalar `requests` (por si no está en `requirements.txt`)
        run: venv\Scripts\python.exe -m pip install requests

      - name: paso8 - Verificar paquetes instalados
        run: venv\Scripts\python.exe -m pip list

      - name: paso9 - Ejecutar script
        run: venv\Scripts\python.exe src/pad_2025/Jazmin_actividad_1.py

      - name: paso10 - Commit y push de cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Test
          commit_user_name: Jazmin Ortiz [GitHub Actions]
          commit_user_email: jazmin.ortiz@est.iudigital.edu.co
          commit_author: Jazmin Ortiz <jazmin.ortiz@est.iudigital.edu.co>
